package com.akhbar24.tests;

import com.akhbar24.utils.BaseTest;
import io.appium.java_client.AppiumBy;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.testng.Assert;
import org.testng.annotations.Test;

import java.util.List;
public class ContactUsTest extends BaseTest {

    private void scrollToText(String visibleText) {
        driver.findElement(AppiumBy.androidUIAutomator(
                "new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(" +
                        "new UiSelector().descriptionContains(\"" + visibleText + "\"))"));
    }

    private void verifyUserIsLoggedIn() {
        boolean isHomeVisible = driver.getPageSource().contains("الرئيسية");
        Assert.assertTrue(isHomeVisible, "❌ لم يتم عرض صفحة الرئيسية بعد تسجيل الدخول.");

        waitForElement(AppiumBy.accessibilityId("القائمة")).click();
        String userStatus = waitForElement(By.xpath("//android.view.View[@content-desc]"))
                .getAttribute("content-desc");
        Assert.assertFalse(userStatus.contains("زائر"), "❌ ما زال المستخدم زائرًا، يبدو أن تسجيل الدخول لم ينجح.");
    }

    @Test
    public void testContactUsFormSubmission() {
        try {
            waitForElement(AppiumBy.accessibilityId("القائمة")).click();
            waitForElement(By.xpath("//android.view.View[@content-desc='تسجيل دخول']")).click();

            List<WebElement> inputs = driver.findElements(By.className("android.widget.EditText"));
            Actions actions = new Actions(driver);
            actions.click(inputs.get(0)).perform();
            inputs.get(0).sendKeys("asilyacoub1@gmail.com");

            actions.click(inputs.get(1)).perform();
            inputs.get(1).sendKeys("123456789");

            waitForElement(AppiumBy.accessibilityId("تسجيل الدخول")).click();
            waitForElement(AppiumBy.accessibilityId("القائمة"));
            verifyUserIsLoggedIn();

            waitForElement(AppiumBy.accessibilityId("القائمة")).click();
            scrollToText("اتصل بنا");
            waitForElement(AppiumBy.accessibilityId("اتصل بنا")).click();

            WebElement nameField = waitForElement(By.xpath("//android.widget.EditText[1]"));
            nameField.click();
            nameField.sendKeys("Asil");

            WebElement emailField = waitForElement(By.xpath("//android.widget.EditText[2]"));
            emailField.click();
            emailField.sendKeys("asilyacoub1@gmail.com");

            WebElement messageField = waitForElement(By.xpath("//android.widget.EditText[3]"));
            messageField.click();
            messageField.sendKeys("This is a test message generated by an automation script");

            waitForElement(AppiumBy.accessibilityId("إرسال")).click();

            By successMsgLocator = By.xpath("//android.view.View[contains(@content-desc, 'تم')]");
            WebElement successMsg = waitForElement(successMsgLocator);

            Assert.assertNotNull(successMsg, "❌ لم تظهر رسالة تأكيد الإرسال.");
        } catch (Exception e) {
            Assert.fail("❌ فشل في إرسال نموذج الاتصال: " + e.getMessage());
        }
    }
}